[package]
name = "tyncan"
version = "0.1.0"
edition = "2024"

[dependencies]
alsa = "0.10.0"
dialoguer = "0.12.0"
console = "0.16.1"
clap = { version = "4.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.12.23", features = ["blocking"] }
